# Generated by Django 2.2 on 2021-05-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us_accidents_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidents',
            name='DATE_ACC',
        ),
        migrations.RemoveField(
            model_name='accidents',
            name='MONTH_DATE',
        ),
    ]
