# Generated by Django 2.2 on 2021-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_accidents_app', '0002_auto_20210503_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
