# Generated by Django 2.2 on 2021-05-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_accidents_app', '0003_auto_20210503_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
